name: Deploy Production

on:
  push:
    tags:
      - 'vp*'

#defaults:
#  run:
#    shell: /usr/bin/zsh --login {0}

jobs:
  deploy:
    runs-on: rpi-pi

    steps:
      - name: who am i
        run: |
          whoami

      - name: who am i
        run: |
          source /home/lil-nas/.zshrc

      - name: Pull latest code
        run: |
          cd /home/lil-nas/projects/SystemVI
          git pull

      - name: Build Laminar
        run: |
          cd /home/lil-nas/projects/SystemVI/website/client
          /home/lil-nas/.bun/bin/bun install
          /home/lil-nas/.bun/bin/bun run build

      - name: Build http4s docker
        run: |
          cd /home/lil-nas/projects/SystemVI/website
          sudo env PATH=$PATH sbt server/Docker/publishLocal

      - name: Copy config and assets
        run: |
          cd /home/lil-nas/projects/SystemVI/website
          cp -r client/dist docker/public
          cp -r server/config/* docker/config

      - name: Restart with Docker Compose
        run: |
          cd /home/lil-nas/projects/SystemVI/website/docker
          sudo docker compose down
          sudo docker compose up -d