name: Print SBT and Bun Versions

on:
  workflow_dispatch:

jobs:
  print-versions:
    runs-on: rpi-pi
    container:
        image: node:20-bookworm
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Change to 11 or 21 depending on your project
          cache: 'sbt'       # Automatically caches ~/.sbt and ~/.ivy2/cache

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Print bun version
        run: bun --version

      - name: Print sbt version
        run: sbt --version
